improve workflow

diff --git a/.github/workflows/automated-linting.yml b/.github/workflows/automated-linting.yml
--- a/.github/workflows/automated-linting.yml
+++ b/.github/workflows/automated-linting.yml
@@ -17,22 +17,26 @@ jobs:
         uses: pnpm/action-setup@v2.2.4
       - run: pnpm i --ignore-scripts
       - run: pnpm run lint
-        id: lint
+        name: Running linter
+        id: eslint
+        # There are currently many linting errors in sites-components.
+        # This is a temporary fix to allow the workflow continue 
+        # while these errors are being addressed.
         continue-on-error: true   
-      - run: echo ${{ steps.lint.outcome }}   
       - run: pnpm run prettier
-      - name: Automated Linting
-        id: automated-linting
+        name: Running prettier
+      - name: Push changes
+        id: push-changes
         uses: EndBug/add-and-commit@v9
         with:
-          message: "Automated linting update"
+          message: "Automated linting/prettier update"
           add: "*"
           push: true
           pull: --rebase --autostash
           default_author: github_actions
       - name: Fail job if push changes
-        if: steps.automated-linting.outputs.pushed == 'true'
-        run: exit 1;
-      - name: Fail on linting error
-        if: steps.lint.outcome == 'failure'
-        run: exit 1;
+        if: steps.push-changes.outputs.pushed == 'true'
+        run: echo "Linting/Prettier changes were made. Changes pushed."; exit 1;
+      - name: Fail job on linting error
+        if: steps.eslint.outcome == 'failure'
+        run: echo "The linter found errors that must be manually addressed. See step, Running linter"; exit 1;
